config/routes.rb
Rails.application.routes.draw do

  root to: 'events#index'

  devise_for :users

  resources :events

  resources :users, only: [:show]

  resources :events do
    resources :attendances
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :admin, class_name: 'User'
  has_many :attendances
  has_many :guests, through: :attendance, class_name: 'User'


  validates :start_date, presence: true
  validates :duration, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :price, presence: true, numericality: { only_integer: true, in: 1..1000 }
  validates :location, presence: true

  def start_is_future?
    valid = self.start_date.to_i > Time.now.to_i
    errors.add(:start_date, "star must be in the future") unless valid
  end
  
  def is_modulo_5?
    valid = self.duration.to_i%5 == 0    
    errors.add(:duration, "duration must be a multiple of 5") unless valid
  end

def end_date
  self.start_date + self.duration.to_i*60 
  
end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :attendances, foreign_key: 'guest_id', class_name: 'Attendance'
  has_many :events, through: :attendance, foreign_key: 'admin_id', class_name: 'Event'


  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!, only: %i[new index]

  def index
    @event = Event.find(params[:event_id])
    @attendances = Attendance.all
  end

  def new
    @attendance = Attendance.create
    @event = Event.find(params[:event_id])
  end 

  def create
    @event = Event.find(params[:event_id])
    @user = current_user
    @stripe_amount = @event.price
    begin
      customer = Stripe::Customer.create({
                                           email: params[:stripeEmail],
                                           source: params[:stripeToken]
                                         })
      charge = Stripe::Charge.create({
                                       customer: customer.id,
                                       amount: @stripe_amount *100,
                                       description: "Achat d'un produit",
                                       currency: 'eur'
                                     })
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_event_attendance_path
    end

    @attendance = Attendance.new(stripe_customer_id: customer.id,
      user: @user,
      event: @event
    )

    if @attendance.save
      redirect_to event_path(params[:event_id])
    else 
      flash.now[:alert] = @attendance.errors.full_messages
      render 'new'
    end

  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :admin_user, only: %i[edit update destroy]
  before_action :authenticate_user!, only: %i[new edit create update destroy]

  def index
    @events = Event.all
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(params_event)
      redirect_to event_path(params[:id])
    else
      flash.now[:alert] = @event.errors.full_messages
      render :edit
    end
  end

  def new
    @event = Event.create
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @attendances = Attendance.all
    @attendances.each do |attendance|
      attendance.destroy if attendance.event_id == @event.id
    end
    @event.destroy
    redirect_to events_path
  end

  def create
    @event = Event.new(admin_id: current_user.id,
                       'title' => params[:event_title],
                       'description' => params[:event_description],
                       'start_date' => params[:event_start_date],
                       'duration' => params[:event_duration],
                       'price' => params[:event_price],
                       'location' => params[:event_location])

    if @event.save
      puts '€' * 50
      puts params
      puts '€' * 50
      redirect_to event_path(Event.all.last.id)
      flash.now[:alert] = 'Yes congrats'
    else
      flash.now[:alert] = @event.errors.full_messages
      render 'new'
    end
  end

  private

  def admin_user
    @event = Event.find(params[:id])
    unless current_user.id == @event.admin_id
      flash[:danger] = "Vous n'êtes pas autorisé à venir dans cette zone"
      redirect_to event_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: [:show]


  def show
    @user = User.find(current_user.id)
    @events = Event.all
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/create.html.erb
<h2>Thanks, you paid <strong><%=  @stripe_amount%></strong>!</h2>

app/views/attendances/index.html.erb
<div class="container marketing">
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default text-left">
        <div class="panel-body">
          <h1 class="text-center text-info">Liste des invités</h1>
        </div>
      </div>
    </div>
    <p class="text-decoration-none"><%= link_to "Modifier l'Event",  edit_event_path(@event.id), class: "btn btn-info" %></p>
    <div class="row ml-5">
      <% @attendances.each do |attendance| %>
        <%if attendance.event_id == @event.id %>
          <div class="col-lg-3 well m-3">
            <img src="https://source.unsplash.com/200x200/?portrait?sig=<%=rand(1..100)%>" 
                alt="avatar" class="rounded-circle img-fluid" style="width: 150px;">
            <h4><%= attendance.user.first_name %></h4>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/attendances/new.html.erb
<h1>Bienvenue sur ma page de paiement !</h1>
<p>Vous avez choisi l'event <%= @event.title %>.</p>
<%= form_tag url_for(action: 'create'), method: "post" do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Son prix est de : <%= @event.price %> €</span>
    </label>
  </article>
  <br/>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-description="Achat d'un produit"
  data-amount=<%= @stripe_amount.to_i * 100 %>
  data-currency="eur"
  data-locale="auto"></script>
<% end %>

app/views/events/edit.html.erb
<%= form_for @event do |f|%>
  <div class='form-group'>
    <label> Titre </label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <label> Description </label>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <label> Date de l'event </label>
    <%= f.datetime_field :start_date, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <label> Durée </label>
    <%= f.text_field :duration, class: 'form-control', type:'number'%>
  </div>
  <div class='form-group'>
    <label> Prix </label>
    <%= f.text_field :price, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <label> Lieu </label>
    <%= f.text_field :location, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= submit_tag "Edit Event" %>  </div>
  <div class="col-sm">
    <%= button_to "Supprimer l'Event", event_path(@event), method: :delete, class: "btn btn-danger"%>
  </div>
<% end %>

app/views/events/index.html.erb
<div class="container marketing">
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default text-left">
        <div class="panel-body">
          <h1 class="text-center text-info">Nos Events</h1>
          <p class="text-decoration-none"><%= link_to 'Créer un Event', new_event_path, class: "btn btn-info" %></p>
        </div>
      </div>
    </div>
    <div class="row ml-5">
      <% @events.each do |event| %>
        <div class="col-lg-3 well m-3">
          <img src="https://source.unsplash.com/200x200/?city?sig=<%=rand(1..100)%>" 
                alt="avatar" class="rounded-circle img-fluid" style="width: 150px;">
          <h4><%= event.title %></h4>
          <div class="col">
            <p class="text-decoration-none"><%= link_to "Voir l'Event", event_path(event), class: "btn btn-info" %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<%= form_tag url_for(action: 'create'), method: "post" do %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <%= label_tag 'Title' %>
  <%= text_field_tag 'event_title', @event.title %>
  <br />
  <%= label_tag 'Description' %>
  <%= text_area_tag 'event_description', @event.description %>
  <br />
  <%= label_tag "Date de l'Event" %>
  <%= date_field_tag 'event_start_date', @event.start_date %>
  <br />
  <%= label_tag "Durée" %>
  <%= text_field_tag 'event_duration', @event.duration %>
  <br />
  <%= label_tag "Prix" %>
  <%= text_field_tag 'event_price', @event.price %>
  <br />
  <%= label_tag "Lieu" %>
  <%= text_field_tag 'event_location', @event.location %>
  <br />



  <%= submit_tag "Create Event" %>
<% end %>

app/views/events/show.html.erb
<%# -------------------------------Content------------------------------- %>
<div class="container text-center">
  <!--   <h1>Voici la page du potin n°<%= params[:id]%></h1>-->
  <div class="row">
    <div class="col-sm-3 well">
      <%# -------------------------------Connected user------------------------------- %>
      <div class="well">
        <img src="https://source.unsplash.com/200x200/?city?sig=<%=rand(1..100)%>" 
                alt="avatar" class="rounded-circle img-fluid" style="width: 150px;">
        <h3><strong><%= @event.admin.email %> </h3>
        </div>
        <div class="well">
          <%# -------------------------------Tags------------------------------- %>
          <%# <p><a href="#">Interests</a></p>
          <p>
            <span class="label label-default">News</span>
            <span class="label label-primary">W3Schools</span>
            <span class="label label-success">Labels</span>
            <span class="label label-info">Football</span>
            <span class="label label-warning">Gaming</span>
            <span class="label label-danger">Friends</span>
          </p> %>
          <%# -------------------------------End Tags------------------------------- %>
          <h3><strong>Ville : </strong></h3>
          <h4><%= @event.location %></h4>
        </div>
        <div >
        </div>
      </div>
      <div class="col-sm-7">
        <div class="row">
          <div class="col-sm-12">
            <div class="panel panel-default text-left">
              <div class="panel-body">
                <h2 class="text-center"><%= @event.title %></h2>
                <p> Description : <%= @event.description %></p>
                <p> Prix : <%= @event.price %>€</p>
                <p> Date de début : <%= @event.start_date %></p>
                <p> nb inscrit : <%= @event.attendances.length %></p>
                <p> Durée : <%= @event.duration %> minutes</p>
                <p> fin de l'évent : <%= @event.end_date %></p>
                <div class="lign"> <hr> </div>
                <div class="row ">
                </div>
              </div>
              <p class="text-decoration-none"><%= link_to "s'inscrire",  new_event_attendance_path(@event.id), class: "btn btn-info" %></p>
              <p class="text-decoration-none"><%= link_to "Mon espace évenement", event_attendances_path(@event.id), class: "btn btn-info" %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>R20220516EventbriteV2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# Bootstrap CSS %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%# Bootstrap CSS Suppl %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <%# Bootstrap JS %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <strong><%= link_to "EventBriteLike", root_path, class: "navbar-brand" %></strong>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "New Event", new_event_path, class: "nav-link" %>
            </li>
          </ul>
          <ul class="navbar-nav navbar-right">
            <li class="nav-item active">
              <div class="dropdown">
                <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-user"></i> Mon compte
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <ul>
                    <% if user_signed_in? %>
                      <li>
                        <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
                      </li>
                      <li>
                        Voici ton email : <%= current_user.email %>
                      </li>

                      <li>
                        <%= link_to "Edit email / password", edit_user_registration_path %>
                      </li>
                    <% else %>
                      <li>
                        <%= link_to "Sign in", new_user_session_path %>
                      </li>
                      <li>
                        <%= link_to "Sign up", new_user_registration_path %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </nav>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<%# -------------------------------Content------------------------------- %>
<div class="container text-center">
  <div class="row">
    <div class="col-sm-3 well">
      <%# -------------------------------Connected user------------------------------- %>
      <div class="well">
        <img src="https://source.unsplash.com/200x200/?portrait?sig=<%=rand(1..50)%>" 
                alt="avatar" class="rounded-circle img-fluid" style="width: 150px;">
        <h3><strong> User : </strong></h3>
        <h4><%= @user.first_name %> <%= @user.last_name %></h4>
      </div>
      <div>
        <%# -------------------------------Tags------------------------------- %>
        <%# <p><a href="#">Interests</a></p>
          <p>
            <span class="label label-default">News</span>
            <span class="label label-primary">W3Schools</span>
            <span class="label label-success">Labels</span>
            <span class="label label-info">Football</span>
            <span class="label label-warning">Gaming</span>
            <span class="label label-danger">Friends</span>
          </p> %>
        <%# -------------------------------End Tags------------------------------- %>
      </div>
    </div>
    <div class="col-sm-7">
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default text-left">
            <div class="panel-body">
              <h2 class="text-center">Plus d'informations sur cet utilisateur</h2>
              <h3>Description : <%= @user.description %></h3>
              <h3><span class="fas fa-envelope-open"></span><%= @user.email %></h3>
              <%= link_to "Modifier les informations de connexion", edit_user_registration_path, class: "btn btn-info" %>
            </div>
          </div>
        </div>
      </div>



      <% @events.each do |event| %>
        <% if event.admin_id == current_user.id%>
          <div class="row d-flex justify-content-end">
            <div class="col-sm-9 d-flex">
              <div class="well m-5">
                <b><%= event.title %></b>
                <p class="text-decoration-none"><%= link_to "Voir l'Event", event_path(event), class: "btn btn-info" %></p>
              </div>
            </div>
          </div>
        <% else %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>